Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/EndOfLine:
  EnforcedStyle: lf

#Style/QuotedSymbols:
# Enabled: false

#Style/StringLiterals:
# Enabled: false

#Style/FrozenStringLiteralComment:
#  Enabled: false
